blog/urls.py
from django.urls import path

from blog.views.comment import CommentCreate
from blog.views.home import home
from blog.views.post import PostView, PostCreate, PostUpdate, PostDelete
from blog.views.home import nav
from blog.views.files import BasicUploadView, download_file, delete_file
from .views.meetings import MeetingCreate
from .views.meetingsignin import MeetingSignin
from .views.meetingsignout import meetingSignOut
from .views.endmeeting import end_meeting
from .views.stats import stats

app_name = 'blog'
urlpatterns = [
    # ex: /blog/files
    path('files', BasicUploadView.as_view(), name='upload_file'),
    # ex: /blog/files/something.jpg
    path('files/<str:pk>.<str:ext>', download_file, name='download_file'),
    # path('files/<str:pk>.<str:ext>/update/', update_file, name='update_file'),
    path('files/<str:pk>.<str:ext>/delete/', delete_file, name='delete_file'),
    # In case people use the old path in a blog entry
    path('blog/files/<str:pk>.<str:ext>', download_file, name='download_file_blog'),
    # ex: /blog/
    path('', home, name='home'),
    # ex: /blog/dusan
    path('user/<str:username>', home, name='user_posts'),
    # ex: /blog/post/5/
    path('post/<int:pk>/', PostView.as_view(), name='post'),
    # ex: /blog/post/create/
    path('post/create/', PostCreate.as_view(), name='create_post'),
    # ex: /blog/post/5/update/
    path('post/create/<int:pk>/update', PostUpdate.as_view(), name='update_post'),
    # ex: /blog/post/5/delete/
    path('post/<int:pk>/delete/', PostDelete.as_view(), name='delete_post'),
    # ex: /blog/post/5/comment/
    path('post/<int:pk>/comment/', CommentCreate.as_view(), name='create_comment'),
    path('meeting', MeetingCreate.as_view(), name="create_meeting"),
    path('meeting/stats', stats, name="stats"),
    path('meeting/<int:pk>/end', end_meeting, name='end_meeting'),
    path('meeting/<int:pk>/', MeetingSignin.as_view(), name='signin'),
    path('signout/<int:signId>/', meetingSignOut, name='signout'),
    path('<str:link>', nav, name='nav'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('nested_admin/', include('nested_admin.urls')),
    path('robots.txt', lambda request: redirect('/static/blog/robots.txt', permanent=True)),
    path('favicon.ico', lambda request: redirect('/static/blog/Logo.ico', permanent=True)),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='blog/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='blog:home'), name='logout'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='blog/login.html'), name='login-account'),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='blog:home'), name='logout-account'),
    # path('register/', RegisterView.as_view(), name='register'),
    path('', include('django.contrib.auth.urls')),
    path('', include('blog.urls')),
]

rlsite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls)]

blog/views/comment.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView
from django.shortcuts import Http404
from blog.models.comment import Comment
from blog.models.post import Post
from django.contrib.auth.mixins import PermissionRequiredMixin


class CommentCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Comment
    fields = ['body']
    template_name = 'blog/create_comment.html'
    login_url = reverse_lazy('login')
    permission_required = "blog.comment_gui_can_comment"

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = Post.objects.get(id=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:post', kwargs={'pk': self.kwargs['pk']})

blog/views/endmeeting.py
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404, redirect
from ..models.signin import Signin
from ..models.meeting import Meeting
from django.http import HttpResponse
from django.utils import timezone
from ..forms import PasswordForm


@permission_required("blog.meeting_gui_can_create")
def end_meeting(request, pk):
    meeting = get_object_or_404(Meeting, pk=pk)

    if request.method != 'POST':
        return HttpResponse('expected POST', status=400)

    if meeting.end_time is not None and meeting.end_time < timezone.now():
        return HttpResponse('meeting already over', status=500)

    form = PasswordForm(request.POST)
    if form.is_valid():
        if not request.user.check_password(form.cleaned_data['passwd']):
            return HttpResponse('bad password', status=500)

        meeting.end_time = timezone.now()
        meeting.save()

        return redirect("/")
    else:
        return HttpResponse('bad password', status=500)

blog/views/files.py
from blog.models.files import Files
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse, HttpResponseNotAllowed
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views import View
from ..forms import UpdateFileForm
from django.views.decorators.cache import cache_page
from django.urls import reverse
from ..forms import UploadFileForm, DeleteForm
from ..models import Files
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.core.paginator import Paginator


class BasicUploadView(LoginRequiredMixin, View):
    def get(self, request):
        files_list = Files.objects
        if request.user.has_perm('files_gui_all_list'):
            files_list = files_list.order_by('-pub_date').all()
        elif request.user.has_perm('files_gui_own_list'):
            files_list = files_list.filter(user=request.user).order_by('-pub_date').all()
        else:
            files_list = []

        paginator = Paginator(files_list, 10)
        page = request.GET.get('page', 1)
        files = paginator.get_page(page)

        for fil in files:
            fil.can_delete = request.user.has_perm('files_gui_all_delete')
            if fil.user == request.user:
                # files[fil.pk]['can_update'] = files[fil.pk]['can_update'] or request.user.has_perm(
                #     'files_gui_own_update')
                fil.can_delete = fil.can_delete or request.user.has_perm('files_gui_own_delete')

        can_create = request.user.has_perm('files_gui_own_create')
        return render(self.request, 'blog/files/index.html', {'files': files, 'can_create': can_create, })

    def post(self, request):
        if not request.user.has_perm('files_gui_own_create'):
            raise PermissionError("You can't upload files")

        files = {'fil': self.request.FILES['file']}

        post = dict(self.request.POST).copy()
        post['title'] = 'Bulk %s' % files['fil'].name

        form = UploadFileForm(post, files)
        if form.is_valid():
            form.instance.user = request.user
            file = form.save()
            data = {'is_valid': True, 'name': file.get_rel_url(), 'url': file.get_absolute_url()}
        else:
            data = {'is_valid': False}
        return JsonResponse(data)


@login_required
def upload_file(request):
    if not request.user.has_perm('files_gui_own_create'):
        raise PermissionError("You can't upload files")

    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES, initial={
            'user': request.user,
        })
        form.instance.user = request.user
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(form.instance.get_absolute_url())
    else:
        form = UploadFileForm()
    return render(request, 'blog/files/upload.html', {'form': form})


@cache_page(60 * 60 * 1)
def download_file(request, pk, ext):
    fil = get_object_or_404(Files, pk=pk)
    if not fil.fil.name.endswith(ext):
        raise Http404()
    response = HttpResponse(fil.fil, content_type=fil.get_content_type())
    response['Content-Disposition'] = 'inline; filename=' + fil.fil.name
    return response


@login_required
def delete_file(request, pk, ext):
    fil = get_object_or_404(Files, pk=pk)
    if not fil.fil.name.endswith(ext):
        raise Http404()
    # This is stupid verbose but super clear
    if fil.user == request.user:
        if request.user.has_perm('files_gui_own_delete') or request.user.has_perm('files_gui_all_delete'):
            # Owns file and has one or both required perms
            pass
        else:
            # Owns file but lacks any perms
            raise HttpResponseNotAllowed()
    else:
        if request.user.has_perm('files_gui_all_delete'):
            # Doesn't own file and has all delete perm
            pass
        else:
            # Doesn't own file and lacks all perms
            raise HttpResponseNotAllowed()
    if request.method == 'POST':
        form = DeleteForm(request.POST, request.FILES)
        if form.is_valid():
            fil.delete()
            return HttpResponseRedirect(reverse('blog:upload_file'))
    else:
        form = DeleteForm()
    return render(request, 'blog/files/delete.html', {'form': form, 'fil': fil})

# @login_required
# def update_file(request, pk, ext):
#     fil = get_object_or_404(Files, pk=pk)
#     if not fil.fil.name.endswith(ext):
#         raise Http404()
#
#     # This is stupid verbose but super clear
#     if fil.user == request.user:
#         if request.user.has_perm('files_gui_own_update') or request.user.has_perm('files_gui_all_update'):
#             # Owns file and has one or both required perms
#             pass
#         else:
#             # Owns file but lacks any perms
#             raise HttpResponseNotAllowed()
#     else:
#         if request.user.has_perm('files_gui_all_update'):
#             # Doesn't own file and has all delete perm
#             pass
#         else:
#             # Doesn't own file and lacks all perms
#             raise HttpResponseNotAllowed()
#
#     if request.method == 'POST':
#         form = UpdateFileForm(request.POST, request.FILES)
#         if form.is_valid():
#             fil.title = form.cleaned_data['title']
#             if form.cleaned_data.get('fil', None):
#                 fil.fil = form.cleaned_data.get('fil')
#             # Don't overwrite the file owner
#             # fil.user = request.user
#             fil.pub_date = timezone.now()
#             fil.save()
#             return HttpResponseRedirect(fil.get_absolute_url())
#     else:
#         form = UpdateFileForm(initial={
#             'title': fil.title,
#         })
#     return render(request, 'blog/files/update.html', {'form': form})

blog/views/home.py
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import render, Http404

from blog.models.post import Post
from blog.models.nav import Nav
from blog.models.maintext import MainText

NUM_OF_POSTS = 5


def home(request, username=None):
    first_name = ''
    last_name = ''
    user = None
    main_text = MainText.objects.filter(text_type='Main Page').order_by('pk')[0]
    if username:
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            raise Http404()
        first_name = user.first_name
        last_name = user.last_name
        post_list = Post.objects.filter(user=user)
    else:
        post_list = Post.objects.all()

    post_list = post_list.order_by('-pub_date')

    paginator = Paginator(post_list, NUM_OF_POSTS)  # Show NUM_OF_PAGES posts per page
    page = request.GET.get('page')

    posts = paginator.get_page(page)

    return render(request, 'blog/home.html', {'posts': posts,
                                              'first_name': first_name,
                                              'last_name': last_name,
                                              'main_text': main_text,
                                              'postuser': user,
                                              })


def nav(request, link):
    try:
        nav_item = Nav.objects.get(link=link);
        return render(request, 'blog/nav.html', {"nav": nav_item})
    except Nav.DoesNotExist:
        raise Http404()

blog/views/meetings.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import forms
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView
from ..models.member import Member
from django.shortcuts import Http404, render
from blog.models.comment import Comment
from blog.models.meeting import Meeting, MeetingType
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from datetime import timedelta
from django.http import Http404
from django.forms.fields import MultipleChoiceField
from django.forms.widgets import CheckboxSelectMultiple
from ..models.team import Team


class SigninForm(forms.Form):
    teams = MultipleChoiceField(
        choices=Team.objects.all().order_by('name').values_list("name", "display_name"),
        widget=CheckboxSelectMultiple,
    )


@permission_required("blog.meeting_gui_can_create")
def meeting(request):
    form = SigninForm(request.POST)

    if form.is_valid():
        m = Meeting(user=request.user)
        m.save()
        for choice in form.cleaned_data['teams']:
            ch = MeetingType(meeting=m, team=Team.objects.get(name=choice))
            ch.save()
        return HttpResponseRedirect(reverse('blog:signin', kwargs={'pk': m.pk}))

    return render(request, 'blog/create_meeting.html', {"form": form})

blog/views/meetingsignin.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Count
from django.db.models import Q, F
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView

from blog.forms import PasswordForm
from blog.models.meeting import Meeting
from blog.models.member import Member
from blog.models.signin import Signin
from ..models.team import Team


class MeetingSignin(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Signin
    fields = ['user']
    template_name = 'blog/signin.html'
    login_url = reverse_lazy('login')
    permission_required = "blog.meeting_gui_can_create"

    def form_valid(self, form):
        form.instance.meeting = Meeting.objects.get(pk=self.kwargs['pk'])

        if form.instance.user.team not in form.instance.meeting.meetingtype_set.all():
            return HttpResponse("not in list of teams for the meeting", status=500)

        if form.instance.meeting.start_time > timezone.now():
            return HttpResponse('meeting has not started', status=500)

        if form.instance.meeting.end_time is not None and form.instance.meeting.end_time < timezone.now():
            return HttpResponse('meeting has ended', status=500)

        ret = super().form_valid(form)
        return ret

    def get_success_url(self):
        return reverse('blog:signin', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        ctx = super(MeetingSignin, self).get_context_data(**kwargs)
        ctx['meeting'] = Meeting.objects.get(pk=self.kwargs['pk'])
        ctx['teams'] = [i.team for i in
                        Meeting.objects.get(pk=self.kwargs['pk']).meetingtype_set.all().order_by('team__display_name')]
        signins = Signin.objects.filter(meeting=Meeting.objects.get(pk=self.kwargs['pk']), end_time__isnull=True).all()
        usr = Member.objects.annotate(signin_count=Count(F('signin'))).filter(
            ~Q(signin__in=signins) | Q(signin_count=0)).filter(
            Q(team__in=[i.team for i in
                        Meeting.objects.get(pk=self.kwargs['pk']).meetingtype_set.all().order_by('team__display_name')])
        ).order_by("name", "team")
        ctx['form'].fields['user'].queryset = usr

        ctx['signed_in'] = {}
        for team in Team.objects.all():
            ctx['signed_in'][team.display_name] = Signin.objects.filter(
                end_time__isnull=True,
                user__team=team,
                meeting=Meeting.objects.get(pk=self.kwargs['pk']),
            ).order_by("user__name").all()

        ctx['pw_form'] = PasswordForm()
        return ctx

blog/views/meetingsignout.py
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404, redirect
from ..models.signin import Signin
from ..models.meeting import Meeting
from django.http import HttpResponse
from django.utils import timezone


@permission_required("blog.meeting_gui_can_create")
def meetingSignOut(request, signId):
    user_signin = get_object_or_404(Signin, pk=signId)

    if user_signin.end_time is not None:
        return HttpResponse('user already signed out', status=500)

    if user_signin.meeting.end_time is not None and user_signin.meeting.end_time < timezone.now():
        return HttpResponse('meeting already over', status=500)

    user_signin.end_time = timezone.now()
    user_signin.save()

    return redirect("/meeting/%d/" % user_signin.meeting.id)

blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="container">
        <p>Lorem ipsum</p>
    </div>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
{% load cache %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% cache 600 title %}
        <title>
        {% for title in base_title %}
            {{ title.body }}{% if not forloop.last %}&nbsp;|&nbsp;{% endif %}
        {% empty %}
            RoboLoCo
        {% endfor %}
    {% endcache %}
    &nbsp;|&nbsp;
    {% block title %}
        {% for dtitle in default_title %}
            {{ dtitle.body }}{% if not forloop.last %}&nbsp;|&nbsp;{% endif %}
        {% empty %}
            Team 5338
        {% endfor %}
    {% endblock %}
    </title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="/static/blog/Logo.ico">
    <link rel="stylesheet" href="https://bootswatch.com/4/pulse/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

    {% block pre %}
    {% endblock %}
</head>


<!-- navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary bd-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:home' %}">
            <img src="/static/Logo.svg" width="30" height="30" class="d-inline-block align-top"/>&nbsp;RoboLoCo
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav mr-auto">
                {% for nav in nav_items %}
                    <!--Nav={{ nav.pk }}-->
                    {% if nav.has_children %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ nav.title }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'blog:nav' nav.link %}">{{ nav.title }}</a>
                                <div class="dropdown-divider"></div>
                                {% for nav_child in nav.kids %}
                                    <a class="dropdown-item" href="{% url 'blog:nav' nav_child.link %}">
                                        {{ nav_child.title }}
                                    </a>
                                {% empty %}
                                    <!--Oops-->
                                {% endfor %}
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:nav' nav.link %}">{{ nav.title }}</a>
                        </li>
                    {% endif %}

                {% endfor %}

            </ul>
            {% block navbar %}
            {% endblock %}
            <!-- show Meeting menu only if user is authenticated -->
            {% if perms.blog.meeting_gui_can_create %}
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Meetings </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown3">
                            <a class="dropdown-item" href="{% url 'blog:create_meeting' %}">New Meeting</a>
                            {% if perms.blog.meeting_gui_can_view %}
                                <a class="dropdown-item" href="{% url 'blog:stats' %}">Meeting Stats</a>
                            {% endif %}
                            {% for meeting in meetings %}
                                <a class="dropdown-item"
                                   href="{% url 'blog:signin' meeting.id %}">{{ meeting.user }}
                                    | {{ meeting.start_time }} [{{ meeting.signin_count }}]</a>
                            {% endfor %}
                        </div>
                    </li>
                </ul>
            {% endif %}
            {% cache 600 navbar HEROKU_RELEASE_VERSION user %}
                <ul class="nav navbar-nav ml-auto">
                    <!-- show management menu only if user is authenticated -->
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Management </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                                <a class="dropdown-item" href="{% url 'blog:user_posts' user.username %}">My Posts</a>
                                <a class="dropdown-item" href="{% url 'blog:create_post' %}">New Post</a>
                                <a class="dropdown-item" href="{% url 'blog:upload_file' %}">File Management</a>
                                {% if user.is_staff %}
                                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                                {% endif %}
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'logout' %}">Sign Out</a>
                            </div>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            {% endcache %}
        </div>
    </div>
</nav>


<body>

<div class="container-fluid">
    <div class="row flex-xl-nowrap">
        <main class="col-12 bd-content" role="main">
            {% block content %}{% endblock %}
        </main>
    </div>
</div>

<hr>

<!-- footer -->

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <!--Manual Footer-->
            {% block footer %}{% endblock %}
            <!--Footers-->
            {% cache 600 footer user HEROKU_RELEASE_VERSION %}
                {% for foot in footer %}
                    <div class="text-center">
                        <!--Footer={{ foot.pk }}-->
                        {% autoescape off %}
                            {{ foot.body }}{% if not forloop.last %}&nbsp;|&nbsp;{% endif %}
                        {% endautoescape %}
                    </div>
                {% endfor %}
                <!-- Logged user info -->
                {% if user.is_superuser %}
                    <p class="text-center">
                        Superuser: {{ user.username }}&nbsp;&nbsp;&nbsp;Version: {{ HEROKU_RELEASE_VERSION }}
                        / {{ HEROKU_SLUG_COMMIT }}
                    </p>
                {% elif user.is_staff %}
                    <p class="text-center">
                        Staff User: {{ user.username }}
                    </p>
                {% elif user.is_authenticated %}
                    <p class="text-center">
                        Current User: {{ user.username }}
                    </p>
                {% else %}
                    <p class="text-center">
                        <a href="mailto:contact@roboloco.org">contact@roboloco.org</a>
                    </p>
                {% endif %}

            {% endcache %}

        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
{% block post %}
{% endblock %}
</body>
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load markdownify %}
{% load blog_filters %}

{% block content %}
    <div class="page-header" id="banner">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h1 class="display-3">RoboLoCo</h1>
                <p class="lead">Driving you crazy since 2013</p>
            </div>
            <div class="container text-center">
                <img src="/static/blog/Home.jpg" width="90%">
            </div>

        </div>
        <div class="row">
            <div class="container text-center">
                <p class="lead">{{ main_text.body|linebreaksbr }}</p>
            </div>
        </div>
        <!-- Show this section only for User Blog view -->
        {% if postuser %}
            <div class="container">
                <div class="jumbotron">
                    <h1 class="display-4">{{ postuser.pk|human_name }}'s Posts</h1>
                </div>
            </div>
        {% endif %}

        <!-- Show List of Posts -->
        <div class="container">
            {% for post in posts %}
                <div class="jumbotron">

                    <!-- Post title -->
                    <h1 class="display-4"><a href="{% url 'blog:post' post.pk %}">{{ post.title }}</a></h1>

                    <p class="lead"> Created {{ post.pub_date|timesince }} ago by
                        <a href="{% url 'blog:user_posts' post.user.username %}">
                            {{ post.user.pk|human_name }}
                        </a>
                    </p>
                    <hr class="my-4">
                    <!-- Post body -->
                    <div>{{ post.body|markdownify }}</div>
                </div>
            {% endfor %}
        </div>

        <!-- Pagination -->
        <div class="pagination">
            {% if posts.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ posts.previous_page_number }}">previous</a>
            {% endif %}

            {% if posts.paginator.num_pages != 1 %}
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
            {% endif %}

            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">next</a>
                <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </div>
    </div>
{% endblock content %}

blog/templates/blog/nav.html
{% extends "blog/base.html" %}
{% load markdownify %}

{% block content %}
    <div class="container">
        <p>{{ nav.body|markdownify }}</p>
    </div>
{% endblock content %}

blog/templates/blog/post.html
{% extends "blog/base.html" %}
{% load markdownify %}
{% load blog_filters %}

{% block content %}

    <div class="container-flex">

        <!-- Post -->
        <div class="jumbotron">

            <!-- Post title -->
            <h1 class="display-4">{{ post.title }}</h1>

            <p class="lead"> Created {{ post.pub_date }} by
                <a href="{% url 'blog:user_posts' post.user.username %}">
                    {{ post.user.pk|human_name }}
                </a>
            </p>
            <hr class="my-4">
            <!-- Post body -->
            <div>{{ post.body|markdownify }}</div>

            <!-- Show Update and Delete button only if User is the owner of the Post -->
            {% if post.user == user %}
                <div class="row">

                    <!-- Delete button -->
                    <a href="{% url 'blog:delete_post' post.pk %}" class="col-md-2 pull-right">
                        <button type="button" class="btn btn-primary btn-block">Delete</button>
                    </a>

                    <!-- Update button -->
                    <a href="{% url 'blog:update_post' post.pk %}" class="col-md-2 pull-right">
                        <button type="button" class="btn btn-primary btn-block">Update</button>
                    </a>

                </div>
            {% endif %}

        </div>

        <h2>Comments:</h2>

        <!-- Comments -->
        {% for comment in comments %}
            <div class="well">

                <div> Created {{ comment.pub_date }} by
                    <a href="{% url 'blog:user_posts' comment.user.username %}">
                        {{ comment.user.pk|human_name }}
                    </a>
                </div>

                <!-- Comment body -->
                <p> {{ comment.body|linebreaks }}</p>

            </div>
        {% endfor %}

        <!-- Show Comment button only if User is authenticated -->
        {% if user.is_authenticated %}

            <!-- Comment button -->
            <a href="{% url 'blog:create_comment' post.pk %}" class="col-md-2 pull-right">
                <button type="button" class="btn btn-primary btn-block">Comment</button>
            </a>

        {% endif %}

    </div>
{% endblock content %}